from bs4 import BeautifulSoup
import requests
import csv
import re
import html
import os
from typing import Optional, List, Tuple
import multiprocessing
from functools import partial
from tqdm import tqdm

# Define the keywords to search for
KEYWORDS = [
    "commercial construction", "general contractor", "construction management", "construction services", 
    "project management", "contracting", "construction firm", "building contractor", "developer", 
    "general construction", "contractor services", "professional services", "project developer", 
    "commercial development", "commercial building", "retail construction", "industrial construction", 
    "office space construction", "tenant improvements", "structural engineering", 
    "interior buildouts", "design-build", "pre-construction services", "site development", "ground-up construction", 
    "General Contractors", "Commercial", "Healthcare", "industrial", "keywords",
"construction",
"commercial",
"response",
"context",
"model",
"created_at",
"done_reason",
"total_duration",
"load_duration",
"prompt_eval_count",
"prompt_eval_duration",
"eval_count",
"eval_duration",
"general",
"contractor",
"design",
"build",
"services",
"management",
"keywords",
"projects",
"relevant",
"building",
"found",
"project",
"company",
"residential",
"renovation",
"remodeling",
"development",
"contracting",
"quality",
"industrial",
"custom",
"retail",
"facilities",
"renovations",
"service",
"tenant",
"office",
"engineering",
"solutions",
"buildings",
"clients",
"industry",
"family",
"planning",
"including",
"improvements",
"safety",
"homes",
"contractors",
"interior",
"concrete",
"business",
"maintenance",
"expertise",
"energy",
"healthcare",
"experience",
"multi",
"property",
"facility",
"consulting",
"systems",
"roofing",
"about",
"multifamily",
"government",
"luxury",
"customer",
"hospitality",
"website",
"installation",
"estate",
"process",
"remodels",
"value",
"housing",
"ground",
"appears",
"kitchen",
"medical",
"public",
"commitment",
"builders",
"control",
"improvement",
"owned",
"additions",
"restoration",
"spaces",
"information",
"preconstruction",
"community",
"content",
"based",
"client",
"builder",
"infrastructure",
"steel",
"testimonials",
"civil",
"space",
"water",
"needs",
"educational",
"approach",
"licensed",
"subcontractors",
"sustainable",
"contact",
"years",
"professional",
"architectural",
"offers",
"satisfaction",
"repair",
"exterior",
"historic",
"structural",
"excellence",
"craftsmanship",
"partner",
"electrical",
"carpentry",
"provides",
"properties",
"municipal",
"excavation",
"budget",
"environmental",
"attention",
"modular",
"range",
"compliance",
"remodel",
"storage",
"restaurant",
"detail",
"metal",
"center",
"various",
"noverall",
"corporate",
"certified",
"institutional",
"owner",
"education",
"manager",
"delivering",
"single",
"materials",
"solar",
"bathroom",
"state",
"manufacturing",
"exceptional",
"relationships",
"restaurants",
"scheduling",
"utilities",
"small",
"trusted",
"builds",
"points",
"estimating",
"communities",
"centers",
"federal",
"provided",
"mechanical",
"built",
"marketing",
"sustainability",
"utility",
"capital",
"demolition",
"overview",
"framing",
"equipment",
"effective",
"delivery",
"include",
"completed",
"architecture",
"green",
"contracts",
"structures",
"turnkey",
"plumbing",
"painting",
"operations",
"communication",
"features",
"results",
"program",
"comprehensive",
"repairs",
"mixed",
"working",
"efficient",
"apartment",
"professionalism",
"strong",
"specific",
"finish",
"florida",
"heavy",
"local",
"works",
"managers",
"developments",
"budgeting",
"experienced",
"hotel",
"customers",
"professionals",
"engineered",
"reputation",
"satisfied",
"integrated",
"support",
"group",
"master",
"technology",
"efficiency",
"phase",
"related",
"damage",
"procurement",
"reliable",
"values",
"underground",
"security",
"scale",
"remediation",
"sector",
"focus",
"upgrades",
"workmanship",
"permitting",
"restorations",
"ensuring",
"while",
"through",
"installations",
"provide",
"texas",
"financial",
"throughout",
"units",
"nhere",
"programs",
"private",
"experts",
"offered",
"analysis",
"benefits",
"partners",
"interiors",
"warehouse",
"subcontractor",
"offices",
"institutions",
"selection",
"architects",
"contract",
"flooring",
"called",
"living",
"providing",
"every",
"worked",
"greene",
"administration",
"standards",
"school",
"preservation",
"includes",
"businesses",
"unique",
"inspections",
"national",
"nsome",
"integrity",
"schedule",
"foundation",
"could",
"affordable",
"field",
"members",
"certification",
"urban",
"highlighting",
"within",
"friendly",
"would",
"sales",
"coordination",
"millwork",
"companies",
"positive",
"investment",
"large",
"homeowners",
"training",
"format",
"complex",
"mission",
"veteran",
"growth",
"other",
"track",
"ashland",
"renewable",
"insured",
"health",
"finishes",
"optimization",
"corporation",
"paving",
"drainage",
"hotels",
"insurance",
"across",
"representation",
"owners",
"arizona",
"plants",
"section",
"landscaping",
"software",
"house",
"committed",
"expectations",
"award",
"webpage",
"halls",
"informazioni",
"asset",
"storm",
"landscape",
"smart",
"performance",
"rehabilitation",
"treatment",
"trust",
"emergency",
"distribution",
"drywall",
"bespoke",
"premier",
"fabrication",
"class",
"outdoor",
"happy",
"practices",
"engineer",
"products",
"product",
"senior",
"material",
"successful",
"looking",
"deliver",
"orion",
"engineers",
"replacement",
"perform",
"opportunities",
"staff",
"showcase",
"certifications",
"reviews",
"several",
"advertise",
"purple",
"bonded",
"wastewater",
"point",
"savings",
"erection",
"agencies",
"vertical",
"impact",
"organizations",
"collaborative",
"environments",
"ability",
"bring",
"buildouts",
"common",
"record",
"county",
"execution",
"success",
"today",
"email",
"details",
"complete",
"foundations",
"leading",
"buildout",
"transportation",
"lighting",
"modern",
"clear",
"schools",
"personalized",
"cabinetry",
"specializes",
"capabilities",
"preparation",
"environment",
"offer",
"consultation",
"detailed",
"agency",
"showcasing",
"address",
"system",
"california",
"addition",
"boutique",
"special",
"window",
"minority",
"costs",
"partnering",
"modernization",
"completion",
"please",
"dedicated",
"suppliers",
"siding",
"asphalt",
"designed",
"store",
"market",
"disaster",
"doors",
"strategic",
"phone",
"logistics",
"parks",
"parking",
"marine",
"transparency",
"adaptive",
"always",
"notable",
"inspection",
"modeling",
"specialty",
"exceed",
"winning",
"timely",
"association",
"electric",
"history",
"reputable",
"white",
"acquisition",
"natural",
"skilled",
"driven",
"partnerships",
"version",
"number",
"expansion",
"level",
"labor",
"insights",
"creating",
"highlight",
"collection",
"feasibility",
"johnson",
"dominio",
"focused",
"responsibility",
"shopping",
"grading",
"skills",
"extensive",
"mentioned",
"areas",
"carolina",
"church",
"vision",
"collaboration",
"partnership",
"aspects",
"strengths",
"rooms",
"assist",
"innovation",
"constructability",
"operational",
"expert",
"suggesting",
"dental",
"organization",
"portfolio",
"ensure",
"markets",
"accessibility",
"handling",
"expansions",
"readable",
"touch",
"income",
"cleaning",
"regulatory",
"highlights",
"timelines",
"representative",
"department",
"sections",
"warranty",
"rewritten",
"reliability",
"rental",
"potential",
"masonry",
"designs",
"action",
"countertops",
"technical",
"enterprises",
"torino",
"whois",
"fully",
"south",
"overall",
"hospitals",
"university",
"science",
"highway",
"religious",
"historical",
"districts",
"assurance",
"roofs",
"technologies",
"interested",
"stormwater",
"methods",
"ready",
"future",
"diverse",
"sewer",
"station",
"claims",
"butler",
"learn",
"locations",
"drilling",
"employee",
"seems",
"reuse",
"estimation",
"testing",
"provider",
"durable",
"maricorp",
"showcases",
"accessible",
"agricultural",
"constructions",
"august",
"quotes",
"brief",
"method",
"search",
"since",
"craftsmen",
"superintendents",
"critical",
"oversight",
"evaluation",
"designers",
"schedules",
"returns",
"light",
"decades",
"budgets",
"structure",
"transfer",
"involvement",
"solution",
"emphasis",
"pricing",
"dedication",
"strategy",
"fueling",
"whole",
"commissioning",
"glass",
"however",
"making",
"cabinets",
"vacation",
"license",
"beach",
"supervision",
"variety",
"oregon",
"posts",
"admer",
"siwek",
"involves",
"beautiful",
"matukat",
"deployment",
"acton",
"affiliate",
"icann",
"database",
"division",
"integration",
"superior",
"clearing",
"premium",
"higher",
"panel",
"workforce",
"redevelopment",
"recreation",
"goals",
"recommend",
"native",
"reconstruction",
"traditional",
"removal",
"extract",
"recent",
"style",
"explicitly",
"customized",
"firms",
"windows",
"precision",
"innovative",
"floor",
"enterprise",
"stores",
"multiple",
"challenges",
"informed",
"assistance",
"kitchens",
"established",
"specialized",
"structured",
"extracted",
"first",
"mitigation",
"stations",
"investments",
"finishing",
"lengthy",
"types",
"questions",
"surveying",
"renovating",
"united",
"states",
"sports",
"complexes",
"believe",
"delivered",
"further",
"disabled",
"processes",
"plant",
"together",
"power",
"generation",
"personal",
"zoning",
"change",
"article",
"resource",
"numerous",
"maximize",
"legacy",
"description",
"codes",
"involved",
"furniture",
"president",
"prefabricated",
"applications",
"updates",
"protection",
"qualified",
"dynamic",
"founder",
"themes",
"lists",
"praise",
"heating",
"operated",
"pride",
"something",
"suggests",
"million",
"suggest",
"methodology",
"vacasa",
"individual",
"veterans",
"review",
"start",
"location",
"retrofitting",
"protocols",
"georgia",
"excellent",
"studies",
"clinics",
"clarke",
"automotive",
"dixon",
"mobile",
"developer",
"venues",
"airport",
"revitalization",
"erosion",
"credits",
"sitework",
"charging",
"prioritize",
"better",
"improve",
"teams",
"prime",
"janitorial",
"research",
"faith",
"forward",
"visions",
"subcontracting",
"options",
"techniques",
"convenience",
"streamlined",
"safely",
"wellness",
"bringing",
"layout",
"triple",
"bonding",
"oriented",
"brownstone",
"extensions",
"itself",
"seeking",
"nevada",
"featured",
"informative",
"attract",
"equity",
"condominium",
"assisted",
"reporting",
"nhowever",
"rather",
"northwest",
"financing",
"passive",
"ongoing",
"warehouses",
"ceilings",
"phoenix",
"proud",
"responsive",
"above",
"waste",
"nationwide",
"sdvosb",
"terms",
"hubzone",
"conditions",
"alaska",
"adherence",
"problem",
"director",
"central",
"makes",
"employees",
"communications",
"earthwork",
"basement",
"trade",
"police",
"consultants",
"irrigation",
"defense",
"corps",
"investor",
"timeline",
"importance",
"hiring",
"assess",
"resources",
"environmentally",
"conscious",
"fitness",
"engine",
"ourselves",
"managed",
"place",
"entertainment",
"waterman",
"summary",
"requirements",
"choose",
"waterfront",
"gervais",
"deals",
"tailored",
"descriptions",
"presence",
"clean",
"social",
"licenses",
"developers",
"permits",
"production",
"remodeler",
"standing",
"indoor",
"following",
"dallas",
"improved",
"memar",
"being",
"create",
"transformation",
"monitoring",
"valley",
"assessment",
"responsible",
"trades",
"strategies",
"aspect",
"examples",
"rentals",
"north",
"orange",
"views",
"exclusive",
"neumann",
"lasting",
"closeout",
"source",
"dwelling",
"glazing",
"pressure",
"eastern",
"investors",
"residents",
"receive",
"accredited",
"matthew",
"chicago",
"american",
"combined",
"industries",
"performing",
"selling",
"mayson",
"hanto",
"growspan",
"greenhouse",
"different",
"predevelopment",
"holder",
"audience",
"rimmer",
"roeter",
"processing",
"crews",
"relations",
"advantage",
"approved",
"mantis",
"connected",
"carbon",
"emissions",
"preventive",
"renewal",
"extend",
"directly",
"asbestos",
"leasing",
"preventative",
"woman",
"supplier",
"identified",
"overhead",
"welding",
"finance",
"implied",
"centered",
"started",
"ncontact",
"precisioncontractorsinc",
"vendor",
"apartments",
"physical",
"vehicle",
"evolutions",
"praised",
"particularly",
"aesthetic",
"flexibility",
"changes",
"online",
"condo",
"colorado",
"request",
"contains",
"retrofit",
"condos",
"emphasizes",
"personnel",
"advanced",
"regular",
"around",
"mention",
"rough",
"mentions",
"guide",
"specialties",
"analyze",
"pacific",
"manufacturers",
"occupied",
"minnesota",
"individuals",
"offerings",
"background",
"access",
"additional",
"disclaimer",
"efforts",
"issues",
"crane",
"example",
"serve",
"beyond",
"appreciate",
"introduction",
"supplies",
"pipeline",
"nwith",
"arctic",
"desert",
"helping",
"proposals",
"granite",
"holding",
"current",
"pools",
"driving",
"compressed",
"bathrooms",
"reyman",
"story",
"detention",
"honesty",
"major",
"cloud",
"total",
"leadership",
"staffing",
"associated",
"estates",
"addressing",
"relationship",
"aviation",
"superintendent",
"order",
"climate",
"choosing",
"right",
"entitlement",
"entitlements",
"knowledge",
"sampson",
"country",
"highest",
"designing",
"estimators",
"controls",
"payment",
"existing",
"primary",
"sectors",
"three",
"athletic",
"campus",
"oversees",
"columbia",
"suite",
"insulation",
"final",
"tillit",
"compensation",
"regulated",
"discounts",
"platform",
"emphasizing",
"guaranteed",
"competitive",
"philosophy",
"valuable",
"jennifer",
"portland",
"constructed",
"garage",
"outreach",
"brand",
"developed",
"nthese",
"sheet",
"submit",
"churches",

]

def extract_url_from_html(html_content: str) -> Optional[str]:
    """Extracts and decodes the URL from a given HTML <a> tag."""
    try:
        soup = BeautifulSoup(html_content, 'html.parser')
        a_tag = soup.find('a', href=True)  # Find the first <a> tag with an href attribute
        
        if not a_tag:
            return None
            
        raw_url = a_tag['href']
        
        # Handle JavaScript encoded URLs
        if "javascript:openPopupFocus" in raw_url:
            # Look for both http and https encoded patterns
            url_pattern = r"(?:http|https)%3A%2F%2F[-\w.]+(?:\/[-\w.%]*)*"
            match = re.search(url_pattern, raw_url)
            
            if match:
                encoded_url = match.group(0)
                # Decode the URL
                decoded_url = html.unescape(encoded_url)
                decoded_url = decoded_url.replace('%3A', ':').replace('%2F', '/')
                return decoded_url
                
        # Handle direct URLs
        elif raw_url.startswith(('http://', 'https://')):
            # Extract just the main URL without query parameters
            base_url = re.match(r'https?://[^?\s,\'\"]+', raw_url)
            if base_url:
                return base_url.group(0).rstrip('/')
            return raw_url.split('?')[0].rstrip('/')
        
        # Handle URLs without protocol
        elif raw_url.startswith('www.'):
            return f'http://{raw_url.split("?")[0].rstrip("/")}'
            
        return raw_url.split('?')[0].rstrip('/')
        
    except Exception as e:
        print(f"Error extracting URL: {e}")
        return None

def is_site_live(url: str) -> bool:
    """Check if the site is reachable."""
    try:
        response = requests.head(url, timeout=10)
        return response.status_code < 400  # Site is live if status code is less than 400
    except requests.exceptions.RequestException:
        return False

def scrape_website(url: str) -> Optional[str]:
    """Scrape website content with proper headers."""
    headers = {
        'User-Agent': 'Mozilla/5.0 (compatible; KeywordScraperBot/1.0)',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9',
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Remove unwanted elements
        for element in soup(['script', 'style', 'header', 'footer', 'nav']):
            element.decompose()
            
        # Get text with better formatting
        text = ' '.join([p.get_text(strip=True) for p in soup.find_all(['p', 'h1', 'h2', 'h3', 'article'])])
        return text if text.strip() else None
        
    except requests.exceptions.RequestException as e:
        print(f"Error scraping {url}: {str(e)}")
        return None

def find_keywords(content: str) -> List[Tuple[str, str]]:
    """Find keywords in the content and return their locations."""
    found_keywords = []
    for keyword in KEYWORDS:
        keyword_lower = keyword.lower()
        if keyword_lower in content.lower():
            # Find the index of the keyword in the content
            start_index = content.lower().index(keyword_lower)
            end_index = start_index + len(keyword)
            
            # Get a snippet of text around the keyword for context
            snippet_start = max(0, start_index - 30)  # Get 30 characters before the keyword
            snippet_end = min(len(content), end_index + 30)  # Get 30 characters after the keyword
            context = content[snippet_start:snippet_end].replace('\n', ' ').strip()  # Clean up newlines
            
            # Add the keyword and its context to the found list
            found_keywords.append((keyword, f"Found in content: '{context}'"))
    return found_keywords

def process_row(row: List[str]) -> Optional[List[str]]:
    """Process a single row of data."""
    try:
        if len(row) > 1:
            account_name = row[0].strip()
            raw_html = row[1].strip()

            extracted_url = extract_url_from_html(raw_html)
            if not extracted_url:
                return [account_name, "", "N/A", "Failed to extract a valid URL.", ""]

            if not is_site_live(extracted_url):
                return [account_name, extracted_url, "No", "N/A", "Site is not live"]

            website_content = scrape_website(extracted_url)
            if not website_content:
                return [account_name, extracted_url, "Yes", "N/A", "Scraping failed"]

            keywords_found = find_keywords(website_content)
            if keywords_found:
                keywords_str = ', '.join([kw[0] for kw in keywords_found])
                proof_str = ', '.join([kw[1] for kw in keywords_found])
            else:
                keywords_str = "None"
                proof_str = "N/A"

            return [account_name, extracted_url, "Yes", keywords_str, proof_str]

    except Exception as e:
        return [account_name, "", "N/A", "Error", f"Error: {str(e)}"]

def main():
    # Update input and output paths
    input_file = "inputs/input.csv"  # Update to correct input path
    output_file = "output/stage_1_output.csv"
    
    print(f"\nStarting script...")
    print(f"Looking for input file: {os.path.abspath(input_file)}")
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    print(f"Output will be written to: {os.path.abspath(output_file)}")

    try:
        if not os.path.exists(input_file):
            raise FileNotFoundError(f"Input file not found at: {os.path.abspath(input_file)}")

        # Read all rows from input file
        print("Reading input file...")
        with open(input_file, newline='', encoding='utf-8') as file:
            reader = csv.reader(file)
            header = next(reader)  # Skip header
            print(f"Header found: {header}")
            rows = list(reader)
            print(f"Found {len(rows)} rows to process")

        if not rows:
            print(f"Warning: No data found in {input_file}")
            return

        # Create output file with header
        print("Creating output file...")
        with open(output_file, mode='w', newline='', encoding='utf-8') as output_csv:
            writer = csv.writer(output_csv)
            writer.writerow(['Account Name', 'Website', 'Is Site Live', 'Keywords Found', 'Proof'])

        # Create a pool of workers
        num_processes = min(multiprocessing.cpu_count(), len(rows))  # Don't create more processes than rows
        print(f"\nInitializing {num_processes} worker processes...")
        pool = multiprocessing.Pool(processes=num_processes)

        # Process rows in parallel with progress bar
        print(f"Processing {len(rows)} URLs using {num_processes} processes...")
        results = []
        for row_data in tqdm(pool.imap_unordered(process_row, rows), total=len(rows)):
            if row_data:
                results.append(row_data)

        pool.close()
        pool.join()

        # Write all results at once
        print("\nWriting results to file...")
        with open(output_file, mode='a', newline='', encoding='utf-8') as output_csv:
            writer = csv.writer(output_csv)
            writer.writerows(results)

        # Verify output was written
        if os.path.exists(output_file):
            print(f"\nProcessing complete!")
            print(f"Results processed: {len(results)}")
            print(f"Output written to: {os.path.abspath(output_file)}")
            
            # Check output file size
            file_size = os.path.getsize(output_file)
            print(f"Output file size: {file_size} bytes")
            
            # Read and print first few lines of output
            print("\nFirst few lines of output:")
            with open(output_file, 'r', encoding='utf-8') as f:
                for i, line in enumerate(f):
                    if i < 5:  # Print first 5 lines
                        print(line.strip())
                    else:
                        break
        else:
            print("\nWarning: Output file was not created")

    except FileNotFoundError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        import traceback
        print(traceback.format_exc())

if __name__ == "__main__":
    # Protect against recursive multiprocessing on Windows
    multiprocessing.freeze_support()
    main() 